git checkout website/out/about/index.html
git checkout website/out/ambassadors/index.html
git checkout website/out/cookies/index.html
git checkout website/out/free-fundraising/index.html
git checkout website/out/how-it-works/index.html
git checkout website/out/index3/index.html
git checkout website/out/partners/index.html
git checkout website/out/start/index.html
git checkout website/out/category/animals-nature/index.html
git checkout website/out/category/arts-entertainment/index.html
git checkout website/out/category/community/index.html
git checkout website/out/category/faith-family/index.html
git checkout website/out/category/freedom-of-religion/index.html
git checkout website/out/category/hunger-housing/index.html
git checkout website/out/category/international-travel/index.html
git checkout website/out/category/medical-emergencies/index.html
git checkout website/out/category/memorials/index.html
git checkout website/out/category/pro-life/index.html
git checkout website/out/category/volunteer-mission/index.html
git checkout website/out/category/youth/index.html
git checkout website/out/category/education/index.html
git checkout nodejobs/config/local/default.js
git checkout nodejobs/config/dev/default.js
git checkout website/out/trust-safety/index.html
git checkout website/out/global/index.html
git checkout website/out/maintenance/index.html
git checkout nodejobs/config/auto/default.js
git checkout nodejobs/config/demo/default.js
git checkout nodejobs/config/qa/default.js
git checkout nodejobs/config/dev/default.js
git checkout nodejobs/config/prod/default.js
git checkout nodejobs/config/stage/default.js
git checkout nodejobs/config/fresh/default.js
git checkout website/out/category/traditional-values/index.html
git checkout website/out/crowdfunding/index.html
git checkout website/out/features/organizations/index.html
git checkout website/out/features/peer-to-peer/index.html
git checkout website/out/fundraising-ideas/index.html
git checkout website/out/category/athon/index.html
git checkout website/out/category/fundraising-ideas/index.html
git checkout website/out/about.html
git checkout website/out/features/viralvideo/index.html
git checkout website/out/sampleaccount.html
git checkout website/out/sampleaccount/
git checkout website/out/startclaim/